# version: "3.7"
services:
  db:
    build:
      context: ./db_docker
    container_name: db_app
    command:
      - -p 1221
      # - /db/db.sh
    expose:
      - 1221
    env_file:
      - app/.env
   
  app:
    build:
      context: .
    env_file:
      - app/.env
    container_name: fastapi_app
    command: ["/fastapi_app/startup.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

 