# # version: "3.7"
# services:
#   db:
#     build:
#       context: ./db_docker
#     container_name: db_app
#     restart: always
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data
#     # command:
#     # #   - -p 1221
#     #   - /db/db.sh
#     expose:
#       - 5432
#     env_file:
#       - app/.env
#     networks:
#       - app_network

#   backup:
#     build:
#       context: ./backups
#     container_name: pg_backup_container
#     env_file:
#       - app/.env
#     volumes:
#       - ./backups:/backups  # Directory on host to store backups
#     # entrypoint: [ "sh", "-c", "while true; do sleep 3600; done" ]  # Keeps the container running
#     networks:
#       - app_network
   
#   app:
#     build:
#       context: .
#     env_file:
#       - app/.env
#     container_name: fastapi_app
#     command: ["/fastapi_app/startup.sh"]
#     ports:
#       - 9999:8000
#     depends_on:
#       - db
#     networks:
#       - app_network

# # volumes:
# #   postgres_data:
# #     external: true

# networks:
#   app_network:
#     driver: bridge

 